config/routes.rb
Ss::Application.routes.draw do
  resources :products

  resources :todolists

  resources :strategies

  resources :markets

  resources :monitoredmarkets

  resources :plantypefunds

  resources :policyfunds

  resources :strategiesmarkets

  resources :policies

  resources :plantypes

  resources :products

  resources :clients

  resources :currencies

  resources :plantype_strategies

  resources :plantypestrategyfunds

  resources :companies

  match "/meta"                        => "meta#all"
  match "/meta/:id"                    => "meta#show"
  
  
  match "/feeder/:id"                   => "feeder#show"
  match "/feeder/start/:id"             => "feeder#start"
  match "/feeders/client_update/data"   => "feeder#client_upload"
  match "/feeders/loadfunds/data/"      => "feeder#funds_upload"
  
  match "/calculations/switch"          => "calculations#switch"
  
  match "/Test/Calculations"            => "test#calculations" 
  match "/Test/Test_init_market"        => "test#init_markets"
  match "/Test/Generate_Instructions"   => "test#generate_instructions"
  match "/Test/Uploadtestdata"          => "test#uploadFile"
  match "/Test/Uploadtestdata2"         => "test#uploadFile2"
  match "/Test/DoTest"                  => "test#full_calculations_test"
  match "/Test/InitDB"                  => "test#init_database"
  
   

end

app/models/plantype_strategy.rb
class PlantypeStrategy < ActiveRecord::Base
  attr_accessible :deposit_fund_id, :plantype_id, :plantype_strategy, :plantypestrategyFund_id, :strategy_id
end

app/controllers/plantype_strategies_controller.rb
class PlantypeStrategiesController < ApplicationController
  # GET /plantype_strategies
  # GET /plantype_strategies.json
  def index
    @plantype_strategies = PlantypeStrategy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plantype_strategies }
    end
  end

  # GET /plantype_strategies/1
  # GET /plantype_strategies/1.json
  def show
    @plantype_strategy = PlantypeStrategy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plantype_strategy }
    end
  end

  # GET /plantype_strategies/new
  # GET /plantype_strategies/new.json
  def new
    @plantype_strategy = PlantypeStrategy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plantype_strategy }
    end
  end

  # GET /plantype_strategies/1/edit
  def edit
    @plantype_strategy = PlantypeStrategy.find(params[:id])
  end

  # POST /plantype_strategies
  # POST /plantype_strategies.json
  def create
    @plantype_strategy = PlantypeStrategy.new(params[:plantype_strategy])

    respond_to do |format|
      if @plantype_strategy.save
        format.html { redirect_to @plantype_strategy, notice: 'Plantype strategy was successfully created.' }
        format.json { render json: @plantype_strategy, status: :created, location: @plantype_strategy }
      else
        format.html { render action: "new" }
        format.json { render json: @plantype_strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plantype_strategies/1
  # PUT /plantype_strategies/1.json
  def update
    @plantype_strategy = PlantypeStrategy.find(params[:id])

    respond_to do |format|
      if @plantype_strategy.update_attributes(params[:plantype_strategy])
        format.html { redirect_to @plantype_strategy, notice: 'Plantype strategy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plantype_strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plantype_strategies/1
  # DELETE /plantype_strategies/1.json
  def destroy
    @plantype_strategy = PlantypeStrategy.find(params[:id])
    @plantype_strategy.destroy

    respond_to do |format|
      format.html { redirect_to plantype_strategies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/plantype_strategies_helper.rb
module PlantypeStrategiesHelper
end

app/views/plantype_strategies/_form.html.erb
<%= form_for(@plantype_strategy) do |f| %>
  <% if @plantype_strategy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plantype_strategy.errors.count, "error") %> prohibited this plantype_strategy from being saved:</h2>

      <ul>
      <% @plantype_strategy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :plantype_strategy %><br />
    <%= f.number_field :plantype_strategy %>
  </div>
  <div class="field">
    <%= f.label :plantype_id %><br />
    <%= f.number_field :plantype_id %>
  </div>
  <div class="field">
    <%= f.label :strategy_id %><br />
    <%= f.number_field :strategy_id %>
  </div>
  <div class="field">
    <%= f.label :plantypestrategyFund_id %><br />
    <%= f.number_field :plantypestrategyFund_id %>
  </div>
  <div class="field">
    <%= f.label :deposit_fund_id %><br />
    <%= f.number_field :deposit_fund_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plantype_strategies/edit.html.erb
<h1>Editing plantype_strategy</h1>

<%= render 'form' %>

<%= link_to 'Show', @plantype_strategy %> |
<%= link_to 'Back', plantype_strategies_path %>

app/views/plantype_strategies/index.html.erb
<h1>Listing plantype_strategies</h1>

<table>
  <tr>
    <th>Plantype strategy</th>
    <th>Plantype</th>
    <th>Strategy</th>
    <th>Plantypestrategyfund</th>
    <th>Deposit fund</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @plantype_strategies.each do |plantype_strategy| %>
  <tr>
    <td><%= plantype_strategy.plantype_strategy %></td>
    <td><%= plantype_strategy.plantype_id %></td>
    <td><%= plantype_strategy.strategy_id %></td>
    <td><%= plantype_strategy.plantypestrategyFund_id %></td>
    <td><%= plantype_strategy.deposit_fund_id %></td>
    <td><%= link_to 'Show', plantype_strategy %></td>
    <td><%= link_to 'Edit', edit_plantype_strategy_path(plantype_strategy) %></td>
    <td><%= link_to 'Destroy', plantype_strategy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Plantype strategy', new_plantype_strategy_path %>

app/views/plantype_strategies/new.html.erb
<h1>New plantype_strategy</h1>

<%= render 'form' %>

<%= link_to 'Back', plantype_strategies_path %>

app/views/plantype_strategies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Plantype strategy:</b>
  <%= @plantype_strategy.plantype_strategy %>
</p>

<p>
  <b>Plantype:</b>
  <%= @plantype_strategy.plantype_id %>
</p>

<p>
  <b>Strategy:</b>
  <%= @plantype_strategy.strategy_id %>
</p>

<p>
  <b>Plantypestrategyfund:</b>
  <%= @plantype_strategy.plantypestrategyFund_id %>
</p>

<p>
  <b>Deposit fund:</b>
  <%= @plantype_strategy.deposit_fund_id %>
</p>


<%= link_to 'Edit', edit_plantype_strategy_path(@plantype_strategy) %> |
<%= link_to 'Back', plantype_strategies_path %>