config/routes.rb
Ss::Application.routes.draw do
  resources :products

  resources :todolists

  resources :strategies

  resources :markets

  resources :monitoredmarkets

  resources :plantypefunds

  resources :policyfunds

  resources :strategiesmarkets

  resources :policies

  resources :plantypes

  resources :products

  resources :clients

  resources :currencies

  resources :plantype_strategies

  resources :plantypestrategyfunds

  resources :companies

  match "/meta"                        => "meta#all"
  match "/meta/:id"                    => "meta#show"
  
  
  match "/feeder/:id"                   => "feeder#show"
  match "/feeder/start/:id"             => "feeder#start"
  match "/feeders/client_update/data"   => "feeder#client_upload"
  match "/feeders/loadfunds/data/"      => "feeder#funds_upload"
  
  match "/calculations/switch"          => "calculations#switch"
  
  match "/Test/Calculations"            => "test#calculations" 
  match "/Test/Test_init_market"        => "test#init_markets"
  match "/Test/Generate_Instructions"   => "test#generate_instructions"
  match "/Test/Uploadtestdata"          => "test#uploadFile"
  match "/Test/Uploadtestdata2"         => "test#uploadFile2"
  match "/Test/DoTest"                  => "test#full_calculations_test"
  match "/Test/InitDB"                  => "test#init_database"
  
   

end

app/models/currency.rb
class Currency < ActiveRecord::Base
  attr_accessible :currency_id, :currency_name
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @currencies }
    end
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
    @currency = Currency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/new
  # GET /currencies/new.json
  def new
    @currency = Currency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/1/edit
  def edit
    @currency = Currency.find(params[:id])
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(params[:currency])

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render json: @currency, status: :created, location: @currency }
      else
        format.html { render action: "new" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /currencies/1
  # PUT /currencies/1.json
  def update
    @currency = Currency.find(params[:id])

    respond_to do |format|
      if @currency.update_attributes(params[:currency])
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency = Currency.find(params[:id])
    @currency.destroy

    respond_to do |format|
      format.html { redirect_to currencies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_for(@currency) do |f| %>
  <% if @currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% @currency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :currency_id %><br />
    <%= f.number_field :currency_id %>
  </div>
  <div class="field">
    <%= f.label :currency_name %><br />
    <%= f.text_field :currency_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing currency</h1>

<%= render 'form' %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<h1>Listing currencies</h1>

<table>
  <tr>
    <th>Currency</th>
    <th>Currency name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @currencies.each do |currency| %>
  <tr>
    <td><%= currency.currency_id %></td>
    <td><%= currency.currency_name %></td>
    <td><%= link_to 'Show', currency %></td>
    <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
    <td><%= link_to 'Destroy', currency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Currency', new_currency_path %>

app/views/currencies/new.html.erb
<h1>New currency</h1>

<%= render 'form' %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Currency:</b>
  <%= @currency.currency_id %>
</p>

<p>
  <b>Currency name:</b>
  <%= @currency.currency_name %>
</p>


<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>