config/routes.rb
Ss::Application.routes.draw do
  resources :products

  resources :todolists

  resources :strategies

  resources :markets

  resources :monitoredmarkets

  resources :plantypefunds

  resources :policyfunds

  resources :strategiesmarkets

  resources :policies

  resources :plantypes

  resources :products

  resources :clients

  resources :currencies

  resources :plantype_strategies

  resources :plantypestrategyfunds

  resources :companies

  match "/meta"                        => "meta#all"
  match "/meta/:id"                    => "meta#show"
  
  
  match "/feeder/:id"                   => "feeder#show"
  match "/feeder/start/:id"             => "feeder#start"
  match "/feeders/client_update/data"   => "feeder#client_upload"
  match "/feeders/loadfunds/data/"      => "feeder#funds_upload"
  
  match "/calculations/switch"          => "calculations#switch"
  
  match "/Test/Calculations"            => "test#calculations" 
  match "/Test/Test_init_market"        => "test#init_markets"
  match "/Test/Generate_Instructions"   => "test#generate_instructions"
  match "/Test/Uploadtestdata"          => "test#uploadFile"
  match "/Test/Uploadtestdata2"         => "test#uploadFile2"
  match "/Test/DoTest"                  => "test#full_calculations_test"
  match "/Test/InitDB"                  => "test#init_database"
  
   

end

app/models/strategy.rb
class Strategy < ActiveRecord::Base
  attr_accessible :strategy_filter, :strategy_id, :strategy_initial_switch_percentage, :strategy_name, :strategy_trigger_in, :strategy_trigger_out
end

app/controllers/strategies_controller.rb
class StrategiesController < ApplicationController
  # GET /strategies
  # GET /strategies.json
  def index
    @strategies = Strategy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @strategies }
    end
  end

  # GET /strategies/1
  # GET /strategies/1.json
  def show
    @strategy = Strategy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @strategy }
    end
  end

  # GET /strategies/new
  # GET /strategies/new.json
  def new
    @strategy = Strategy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @strategy }
    end
  end

  # GET /strategies/1/edit
  def edit
    @strategy = Strategy.find(params[:id])
  end

  # POST /strategies
  # POST /strategies.json
  def create
    @strategy = Strategy.new(params[:strategy])

    respond_to do |format|
      if @strategy.save
        format.html { redirect_to @strategy, notice: 'Strategy was successfully created.' }
        format.json { render json: @strategy, status: :created, location: @strategy }
      else
        format.html { render action: "new" }
        format.json { render json: @strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /strategies/1
  # PUT /strategies/1.json
  def update
    @strategy = Strategy.find(params[:id])

    respond_to do |format|
      if @strategy.update_attributes(params[:strategy])
        format.html { redirect_to @strategy, notice: 'Strategy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strategies/1
  # DELETE /strategies/1.json
  def destroy
    @strategy = Strategy.find(params[:id])
    @strategy.destroy

    respond_to do |format|
      format.html { redirect_to strategies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/strategies_helper.rb
module StrategiesHelper
end

app/views/strategies/_form.html.erb
<%= form_for(@strategy) do |f| %>
  <% if @strategy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@strategy.errors.count, "error") %> prohibited this strategy from being saved:</h2>

      <ul>
      <% @strategy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :strategy_id %><br />
    <%= f.number_field :strategy_id %>
  </div>
  <div class="field">
    <%= f.label :strategy_name %><br />
    <%= f.text_field :strategy_name %>
  </div>
  <div class="field">
    <%= f.label :strategy_initial_switch_percentage %><br />
    <%= f.text_field :strategy_initial_switch_percentage %>
  </div>
  <div class="field">
    <%= f.label :strategy_filter %><br />
    <%= f.text_field :strategy_filter %>
  </div>
  <div class="field">
    <%= f.label :strategy_trigger_in %><br />
    <%= f.text_field :strategy_trigger_in %>
  </div>
  <div class="field">
    <%= f.label :strategy_trigger_out %><br />
    <%= f.text_field :strategy_trigger_out %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/strategies/edit.html.erb
<h1>Editing strategy</h1>

<%= render 'form' %>

<%= link_to 'Show', @strategy %> |
<%= link_to 'Back', strategies_path %>

app/views/strategies/index.html.erb
<h1>Listing strategies</h1>

<table>
  <tr>
    <th>Strategy</th>
    <th>Strategy name</th>
    <th>Strategy initial switch percentage</th>
    <th>Strategy filter</th>
    <th>Strategy trigger in</th>
    <th>Strategy trigger out</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @strategies.each do |strategy| %>
  <tr>
    <td><%= strategy.strategy_id %></td>
    <td><%= strategy.strategy_name %></td>
    <td><%= strategy.strategy_initial_switch_percentage %></td>
    <td><%= strategy.strategy_filter %></td>
    <td><%= strategy.strategy_trigger_in %></td>
    <td><%= strategy.strategy_trigger_out %></td>
    <td><%= link_to 'Show', strategy %></td>
    <td><%= link_to 'Edit', edit_strategy_path(strategy) %></td>
    <td><%= link_to 'Destroy', strategy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Strategy', new_strategy_path %>

app/views/strategies/new.html.erb
<h1>New strategy</h1>

<%= render 'form' %>

<%= link_to 'Back', strategies_path %>

app/views/strategies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Strategy:</b>
  <%= @strategy.strategy_id %>
</p>

<p>
  <b>Strategy name:</b>
  <%= @strategy.strategy_name %>
</p>

<p>
  <b>Strategy initial switch percentage:</b>
  <%= @strategy.strategy_initial_switch_percentage %>
</p>

<p>
  <b>Strategy filter:</b>
  <%= @strategy.strategy_filter %>
</p>

<p>
  <b>Strategy trigger in:</b>
  <%= @strategy.strategy_trigger_in %>
</p>

<p>
  <b>Strategy trigger out:</b>
  <%= @strategy.strategy_trigger_out %>
</p>


<%= link_to 'Edit', edit_strategy_path(@strategy) %> |
<%= link_to 'Back', strategies_path %>